# Generated by Django 4.2.4 on 2023-08-17 15:11

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Event', primary_key=True, serialize=False)),
                ('staged_for_deletion', models.BooleanField(default=False)),
                ('owner', models.CharField(max_length=50, verbose_name='')),
                ('headliner', models.CharField(max_length=50, verbose_name='name:')),
                ('date', models.DateField(verbose_name='pick date:')),
                ('time_start', models.TimeField(verbose_name='from:')),
                ('time_end', models.TimeField(verbose_name='to:')),
                ('venue', models.CharField(max_length=50, verbose_name='venue:')),
                ('cover_charge', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default=None, max_length=16, null=True, verbose_name='cover charge?')),
                ('cover_amount', models.CharField(blank=True, max_length=3, null=True, verbose_name='cover amount')),
                ('address_street', models.CharField(max_length=50, verbose_name='street address:')),
                ('address_borough', models.CharField(choices=[('', 'Choose Borough'), ('Brooklyn', 'Brooklyn'), ('The Bronx', 'The Bronx'), ('Queens', 'Queens'), ('Manhattan', 'Manhattan'), ('Staten Island', 'Staten Island')], max_length=50, verbose_name='borough')),
                ('address_zip', models.CharField(blank=True, max_length=5, verbose_name='ZIP')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='phone:')),
                ('map_link', models.CharField(blank=True, max_length=300, null=True, verbose_name='map link:')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='notes:')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
