# Generated by Django 4.2.4 on 2023-08-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='headliner',
            field=models.CharField(max_length=50, verbose_name='name:'),
        ),
    ]
