# Generated by Django 4.2.4 on 2024-04-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_cta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='headliner',
            field=models.CharField(max_length=200, verbose_name='name:'),
        ),
    ]
