# Generated by Django 4.2.4 on 2024-04-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_headliner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cta',
            field=models.CharField(blank=True, max_length=200, verbose_name='cta link:'),
        ),
    ]
