# Generated by Django 4.2.4 on 2024-04-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_cta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cta',
            field=models.CharField(blank=True, max_length=200, verbose_name='(e.g. direct link to buy tickets):'),
        ),
    ]
