# Generated by Django 4.2.4 on 2024-04-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_cta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_charge',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Unknown', 'Unknown')], default=None, max_length=16, null=True, verbose_name='cover charge?'),
        ),
    ]
