# Generated by Django 4.2.4 on 2024-04-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_cta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_amount',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='cover amount'),
        ),
    ]
