# Generated by Django 4.2.4 on 2024-04-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_cover_amount'),
        ('events', '0008_alter_event_cover_charge'),
    ]

    operations = [
    ]
